function [featureTable,outputTable] = generatefunction_task2_256(inputData)
%DIAGNOSTICFEATURES recreates results in Diagnostic Feature Designer.
%
% Input:
%  inputData: A table or a cell array of tables/matrices containing the
%  data as those imported into the app.
%
% Output:
%  featureTable: A table containing all features and condition variables.
%  outputTable: A table containing the computation results.
%
% This function computes features:
%  Case_sigstats/Kurtosis
%  Case_sigstats/PeakValue
%  Case_sigstats/SINAD
%  Case_sigstats/SNR
%  Case_sigstats_1/Kurtosis
%  Case_sigstats_1/PeakValue
%  Case_sigstats_1/SINAD
%  Case_sigstats_1/SNR
%  Case_sigstats_2/Kurtosis
%  Case_sigstats_2/PeakValue
%  Case_sigstats_3/Kurtosis
%  Case_sigstats_3/PeakValue
%  Case_sigstats_4/Kurtosis
%  Case_sigstats_4/PeakValue
%  Case_sigstats_4/SINAD
%  Case_sigstats_4/SNR
%  Case_sigstats_5/Kurtosis
%  Case_sigstats_5/PeakValue
%  Case_sigstats_6/Kurtosis
%  Case_sigstats_6/PeakValue
%
% Frame Policy:
%  Frame name: FRM_1
%  Frame size: 0.256 seconds
%  Frame rate: 0.256 seconds
%
% Organization of the function:
% 1. Compute signals/spectra/features
% 2. Extract computed features into a table
%
% Modify the function to add or remove data processing, feature generation
% or ranking operations.

% Auto-generated by MATLAB on 09-Feb-2024 16:08:55

% Create output ensemble.
outputEnsemble = workspaceEnsemble(inputData,'DataVariables',"Case",'ConditionVariables',"Task2");

% Reset the ensemble to read from the beginning of the ensemble.
reset(outputEnsemble);

% Append new frame policy name to DataVariables.
outputEnsemble.DataVariables = [outputEnsemble.DataVariables;"FRM_1"];

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = "Case";

% Loop through all ensemble members to read and write data.
while hasdata(outputEnsemble)
    % Read one member.
    member = read(outputEnsemble);

    % Read signals.
    Case_full = readMemberData(member,"Case",["TIME","P1","P2","P3","P4","P5","P6","P7"]);

    % Get the frame intervals.
    lowerBound = Case_full.TIME(1);
    upperBound = Case_full.TIME(end);
    fullIntervals = frameintervals([lowerBound upperBound],0.256,0.256,'FrameUnit',"seconds");
    intervals = fullIntervals;

    % Initialize a table to store frame results.
    frames = table;

    % Loop through all frame intervals and compute results.
    for ct = 1:height(intervals)
        % Get all input variables.
        Case = Case_full(Case_full.TIME>=intervals{ct,1}&Case_full.TIME<intervals{ct,2},:);

        % Initialize a table to store results for one frame interval.
        frame = intervals(ct,:);

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P1;
            Kurtosis = kurtosis(inputSignal);
            PeakValue = max(abs(inputSignal));
            SINAD = sinad(inputSignal);
            SNR = snr(inputSignal);

            % Concatenate signal features.
            featureValues = [Kurtosis,PeakValue,SINAD,SNR];

            % Package computed features into a table.
            featureNames = {'Kurtosis','PeakValue','SINAD','SNR'};
            Case_sigstats = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Package computed features into a table.
            featureValues = NaN(1,4);
            featureNames = {'Kurtosis','PeakValue','SINAD','SNR'};
            Case_sigstats = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats},'VariableNames',{'Case_sigstats'})];

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P2;
            Kurtosis = kurtosis(inputSignal);
            PeakValue = max(abs(inputSignal));
            SINAD = sinad(inputSignal);
            SNR = snr(inputSignal);

            % Concatenate signal features.
            featureValues = [Kurtosis,PeakValue,SINAD,SNR];

            % Package computed features into a table.
            featureNames = {'Kurtosis','PeakValue','SINAD','SNR'};
            Case_sigstats_1 = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Package computed features into a table.
            featureValues = NaN(1,4);
            featureNames = {'Kurtosis','PeakValue','SINAD','SNR'};
            Case_sigstats_1 = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats_1},'VariableNames',{'Case_sigstats_1'})];

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P3;
            Kurtosis = kurtosis(inputSignal);
            PeakValue = max(abs(inputSignal));

            % Concatenate signal features.
            featureValues = [Kurtosis,PeakValue];

            % Package computed features into a table.
            featureNames = {'Kurtosis','PeakValue'};
            Case_sigstats_2 = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Package computed features into a table.
            featureValues = NaN(1,2);
            featureNames = {'Kurtosis','PeakValue'};
            Case_sigstats_2 = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats_2},'VariableNames',{'Case_sigstats_2'})];

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P4;
            Kurtosis = kurtosis(inputSignal);
            PeakValue = max(abs(inputSignal));

            % Concatenate signal features.
            featureValues = [Kurtosis,PeakValue];

            % Package computed features into a table.
            featureNames = {'Kurtosis','PeakValue'};
            Case_sigstats_3 = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Package computed features into a table.
            featureValues = NaN(1,2);
            featureNames = {'Kurtosis','PeakValue'};
            Case_sigstats_3 = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats_3},'VariableNames',{'Case_sigstats_3'})];

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P5;
            Kurtosis = kurtosis(inputSignal);
            PeakValue = max(abs(inputSignal));
            SINAD = sinad(inputSignal);
            SNR = snr(inputSignal);

            % Concatenate signal features.
            featureValues = [Kurtosis,PeakValue,SINAD,SNR];

            % Package computed features into a table.
            featureNames = {'Kurtosis','PeakValue','SINAD','SNR'};
            Case_sigstats_4 = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Package computed features into a table.
            featureValues = NaN(1,4);
            featureNames = {'Kurtosis','PeakValue','SINAD','SNR'};
            Case_sigstats_4 = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats_4},'VariableNames',{'Case_sigstats_4'})];

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P6;
            Kurtosis = kurtosis(inputSignal);
            PeakValue = max(abs(inputSignal));

            % Concatenate signal features.
            featureValues = [Kurtosis,PeakValue];

            % Package computed features into a table.
            featureNames = {'Kurtosis','PeakValue'};
            Case_sigstats_5 = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Package computed features into a table.
            featureValues = NaN(1,2);
            featureNames = {'Kurtosis','PeakValue'};
            Case_sigstats_5 = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats_5},'VariableNames',{'Case_sigstats_5'})];

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P7;
            Kurtosis = kurtosis(inputSignal);
            PeakValue = max(abs(inputSignal));

            % Concatenate signal features.
            featureValues = [Kurtosis,PeakValue];

            % Package computed features into a table.
            featureNames = {'Kurtosis','PeakValue'};
            Case_sigstats_6 = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Package computed features into a table.
            featureValues = NaN(1,2);
            featureNames = {'Kurtosis','PeakValue'};
            Case_sigstats_6 = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats_6},'VariableNames',{'Case_sigstats_6'})];

        %% Concatenate frames.
        frames = [frames;frame]; %#ok<*AGROW>
    end

    % Write all the results for the current member to the ensemble.
    memberResult = table({frames},'VariableNames',"FRM_1");
    writeToLastMemberRead(outputEnsemble,memberResult)
end

% Gather all features into a table.
selectedFeatureNames = ["FRM_1/Case_sigstats/Kurtosis","FRM_1/Case_sigstats/PeakValue","FRM_1/Case_sigstats/SINAD","FRM_1/Case_sigstats/SNR","FRM_1/Case_sigstats_1/Kurtosis","FRM_1/Case_sigstats_1/PeakValue","FRM_1/Case_sigstats_1/SINAD","FRM_1/Case_sigstats_1/SNR","FRM_1/Case_sigstats_2/Kurtosis","FRM_1/Case_sigstats_2/PeakValue","FRM_1/Case_sigstats_3/Kurtosis","FRM_1/Case_sigstats_3/PeakValue","FRM_1/Case_sigstats_4/Kurtosis","FRM_1/Case_sigstats_4/PeakValue","FRM_1/Case_sigstats_4/SINAD","FRM_1/Case_sigstats_4/SNR","FRM_1/Case_sigstats_5/Kurtosis","FRM_1/Case_sigstats_5/PeakValue","FRM_1/Case_sigstats_6/Kurtosis","FRM_1/Case_sigstats_6/PeakValue"];
featureTable = readFeatureTable(outputEnsemble,"FRM_1",'Features',selectedFeatureNames,'ConditionVariables',outputEnsemble.ConditionVariables,'IncludeMemberID',true);

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = unique([outputEnsemble.DataVariables;outputEnsemble.ConditionVariables;outputEnsemble.IndependentVariables],'stable');

% Gather results into a table.
outputTable = readall(outputEnsemble);
end
